import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { Lock, Play, Share2 } from "lucide-react";
import { StreamingShell } from "@/components/streaming/StreamingShell";
import { resolveCatalogueKey } from "@/lib/avant-backend";
import { absoluteUrl, publicPageLinks, publicPageMeta, videoObjectSchema } from "@/lib/seo";
import { ArtworkImage } from "@/components/streaming/ArtworkImage";
import { mapResolvedEpisodes } from "@/lib/episodes";

export const Route=createFileRoute("/episode/$slug/$episodeNumber")({
  loader:async({params})=>{const n=Number(params.episodeNumber);if(!Number.isInteger(n)||n<1)throw notFound();const data:any=await resolveCatalogueKey(params.slug).catch(()=>null);const title=data?.title;const seasons=data?.seasons||[],episodes=data?.episodes||[];if(!title||title.content_type!=="series")throw notFound();const ordered=mapResolvedEpisodes(episodes,seasons);const canonicalKeys=new Set(ordered.map((entry:any)=>entry.id||entry.legacyKey).filter(Boolean));const canonicalEpisodes=episodes.filter((candidate:any)=>canonicalKeys.has(candidate.id||candidate.legacy_key));const episode=canonicalEpisodes[n-1];if(!episode)throw notFound();return{item:title,episode,episodeNumber:n};},
  head:({loaderData})=>{if(!loaderData)return{};const{item,episode,episodeNumber}=loaderData,path=`/episode/${item.slug}/${episodeNumber}`,title=`${episode.title} — ${item.title} | Avant Cinema`,description=episode.description||`Watch ${episode.title} from ${item.title} on Avant Cinema.`,image=episode.thumbnail_url||item.backdrop_url||item.poster_url;return{meta:publicPageMeta(path,title,description,image,"video.episode"),links:publicPageLinks(path),scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@graph":[{"@type":"TVEpisode",name:episode.title,description,episodeNumber,url:absoluteUrl(path),image:image?[image]:undefined,partOfSeries:{"@type":"TVSeries",name:item.title,url:absoluteUrl(`/title/${item.slug}`)}},...(episode.vimeo_video_id?[videoObjectSchema({name:episode.title,description,vimeoId:episode.vimeo_video_id||undefined,duration:episode.duration_seconds?pageDuration(episode.duration_seconds):undefined,pagePath:path,episodeNumber,seriesName:item.title,seriesPath:`/title/${item.slug}`,uploadDate:episode.visible_from||episode.created_at,thumbnailUrl:episode.thumbnail_url||undefined})]:[]),{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Avant Cinema",item:absoluteUrl("/")},{"@type":"ListItem",position:2,name:"TV Shows",item:absoluteUrl("/tv-shows")},{"@type":"ListItem",position:3,name:item.title,item:absoluteUrl(`/title/${item.slug}`)},{"@type":"ListItem",position:4,name:episode.title,item:absoluteUrl(path)}]}]})}]}},
  component:EpisodeSharePage,
});
function pageDuration(seconds:number){const m=Math.floor(seconds/60),s=seconds%60;return`${m}:${String(s).padStart(2,"0")}`}
function EpisodeSharePage(){const{item,episode,episodeNumber}=Route.useLoaderData();const key=episode.legacy_key||episode.id;const shareEpisode=async()=>{const path=`/episode/${item.slug}/${episodeNumber}`,url=new URL(path.replace(/^\//,""),document.baseURI).href;try{if(navigator.share)await navigator.share({title:`${episode.title} — ${item.title}`,text:episode.description||`Watch ${episode.title} from ${item.title} on Avant Cinema.`,url});else{await navigator.clipboard.writeText(url);window.alert("Episode link copied.")}}catch(error:any){if(error?.name!=="AbortError")window.alert("Unable to share this episode.")}};const image=episode.thumbnail_url||item.backdrop_url||item.poster_url;return <StreamingShell><main className="mx-auto min-h-[80vh] max-w-5xl px-5 pb-20 pt-28 sm:px-10"><Link to="/title/$slug" params={{slug:item.slug}} className="text-sm text-white/55 hover:text-white">← {item.title}</Link><section className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-surface"><div className="aspect-video bg-black">{image?<ArtworkImage src={image} vimeoVideoId={episode.vimeo_video_id} fallbacks={[item.backdrop_url,item.poster_url]} alt={`${episode.title} thumbnail`} fetchPriority="high" decoding="async" className="size-full object-cover"/>:<div className="grid size-full place-items-center text-white/30">Avant Cinema</div>}</div><div className="p-5 sm:p-8"><p className="eyebrow">{item.title} · Episode {episodeNumber}</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">{episode.title}</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-white/60">{episode.description||`Watch this episode of ${item.title} on Avant Cinema.`}</p><div className="mt-6 flex flex-wrap gap-3"><Link to="/watch/$contentId" params={{contentId:key}} className="inline-flex min-h-12 items-center gap-2 rounded-md bg-white px-5 font-bold text-black">{episode.access_required!==false?<Lock className="size-4"/>:<Play className="size-4 fill-current"/>}{episode.access_required!==false?"View access":"Watch episode"}</Link><button type="button" onClick={()=>void shareEpisode()} className="inline-flex min-h-12 items-center gap-2 rounded-md border border-white/20 px-5 font-bold text-white hover:bg-white/10"><Share2 className="size-4"/>Share</button></div></div></section></main></StreamingShell>}
