import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { StreamingShell } from "@/components/streaming/StreamingShell";
import { getTitles } from "@/lib/site-data";
import { absoluteUrl, publicPageLinks, publicPageMeta } from "@/lib/seo";

const slugify=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export const Route=createFileRoute("/genre/$genre")({
 loader:({params})=>{const all=getTitles().filter(x=>x.available!==false);const items=all.filter(x=>x.genres.some(g=>slugify(g)===params.genre));if(!items.length)throw notFound();const genre=items.flatMap(x=>x.genres).find(g=>slugify(g)===params.genre)||params.genre;return{genre,items};},
 head:({loaderData})=>{if(!loaderData)return{};const path=`/genre/${slugify(loaderData.genre)}`,title=`${loaderData.genre} Movies & Series — Avant Movies`,description=`Explore ${loaderData.genre.toLowerCase()} movies and series on Avant Movies. Discover trailers, story details and titles available to watch.`;return{meta:publicPageMeta(path,title,description,loaderData.items[0]?.backdrop||loaderData.items[0]?.artwork),links:publicPageLinks(path),scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"ItemList",name:title,itemListElement:loaderData.items.map((x,i)=>({"@type":"ListItem",position:i+1,url:absoluteUrl(`/title/${x.slug}`)}))})}]};},
 component:GenrePage
});
function GenrePage(){const{genre,items}=Route.useLoaderData();return <StreamingShell backTo="/" backLabel="Home"><main className="mx-auto min-h-[80vh] max-w-[1500px] px-5 pb-20 pt-28 sm:px-10"><p className="eyebrow">Avant genres</p><h1 className="mt-3 text-5xl font-black sm:text-7xl">{genre}</h1><p className="mt-4 max-w-2xl text-white/60">Explore {genre.toLowerCase()} stories available on Avant Movies.</p><div className="mt-10 grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-4">{items.map(x=><Link key={x.slug} to="/title/$slug" params={{slug:x.slug}} className="group"><div className="aspect-[2/3] overflow-hidden rounded-lg bg-white/5"><img src={x.artwork||x.backdrop} alt={`${x.title} ${x.type==="movie"?"film poster":"series artwork"}`} loading="lazy" className="size-full object-cover transition duration-500 group-hover:scale-105"/></div><h2 className="mt-3 font-bold">{x.title}</h2><p className="text-sm text-white/45">{x.year||""}{x.genres.length?` · ${x.genres.slice(0,2).join(" · ")}`:""}</p></Link>)}</div></main></StreamingShell>}
