import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { StreamingShell } from "@/components/streaming/StreamingShell";
import { getTitles } from "@/lib/site-data";
import { absoluteUrl, publicPageLinks, publicPageMeta } from "@/lib/seo";
const slugify=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export const Route=createFileRoute("/person/$person")({
 loader:({params})=>{const titles=getTitles().filter(x=>x.available!==false);const credits=titles.filter(x=>[...(x.cast||[]),...(x.directors||[]),...(x.creators||[])].some(n=>slugify(n)===params.person));if(!credits.length)throw notFound();const names=credits.flatMap(x=>[...(x.cast||[]),...(x.directors||[]),...(x.creators||[])]);const name=names.find(n=>slugify(n)===params.person)||params.person;return{name,credits};},
 head:({loaderData})=>{if(!loaderData)return{};const path=`/person/${slugify(loaderData.name)}`;const roles=new Set<string>();loaderData.credits.forEach(x=>{if((x.directors||[]).includes(loaderData.name))roles.add("Director");if((x.creators||[]).includes(loaderData.name))roles.add("Creator");if((x.cast||[]).includes(loaderData.name))roles.add("Cast")});const title=`${loaderData.name} — ${[...roles].join(" & ")} | Avant Movies`;const description=`Explore ${loaderData.name}'s film and series credits on Avant Movies, including ${loaderData.credits.slice(0,3).map(x=>x.title).join(", ")}.`;return{meta:publicPageMeta(path,title,description,loaderData.credits[0]?.artwork),links:publicPageLinks(path),scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"ProfilePage","mainEntity":{"@type":"Person","@id":`${absoluteUrl(path)}#person`,name:loaderData.name,url:absoluteUrl(path)},"hasPart":loaderData.credits.map(x=>({"@type":x.type==="movie"?"Movie":"TVSeries",name:x.title,url:absoluteUrl(`/title/${x.slug}`)}))})}]};},
 component:PersonPage
});
function PersonPage(){const{name,credits}=Route.useLoaderData();return <StreamingShell backTo="/" backLabel="Home"><main className="mx-auto min-h-[80vh] max-w-[1400px] px-5 pb-20 pt-28 sm:px-10"><p className="eyebrow">Avant credits</p><h1 className="mt-3 text-5xl font-black sm:text-7xl">{name}</h1><p className="mt-4 max-w-2xl text-white/60">Films and series connected to {name} on Avant Movies.</p><div className="mt-10 grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-4">{credits.map(x=><Link key={x.slug} to="/title/$slug" params={{slug:x.slug}}><div className="aspect-[2/3] overflow-hidden rounded-lg bg-white/5"><img src={x.artwork||x.backdrop} alt={`${x.title} artwork`} loading="lazy" className="size-full object-cover"/></div><h2 className="mt-3 font-bold">{x.title}</h2><p className="text-sm text-white/45">{x.type==="movie"?"Movie":"Series"} · {x.genres.slice(0,2).join(" · ")}</p></Link>)}</div></main></StreamingShell>}
